FROM python:3.10.10-alpine3.17

WORKDIR /app

RUN apk update && apk add postgresql-dev python3-dev libpq-dev gcc musl-dev

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY entrypoint.sh /app_scripts/entrypoint.sh
RUN sed -i 's/\r$//g' /app_scripts/entrypoint.sh
RUN chmod +x /app_scripts/entrypoint.sh

CMD /app_scripts/entrypoint.sh
