FROM python:3.10.10-alpine3.17

WORKDIR /app

RUN apk update && apk add postgresql-dev python3-dev libpq-dev gcc musl-dev

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

CMD python3 manage.py makemigrations && \
    python3 manage.py migrate && \
    python3 manage.py runserver 0.0.0.0:8000